assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDeployment
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
branches:
  master:
    tag:
    increment:
    prevent-increment-of-merged-branch-version: true
  release[/-]:
    tag: beta
  feature[/-]:
    tag: useBranchName
    increment: Inherit
  hotfix[/-]:
    tag: hotfix
  support[/-]:
    tag:
    increment:
    prevent-increment-of-merged-branch-version: true
  develop:
    mode: ContinuousDeployment
    tag: unstable
    increment:
    track-merge-target: true
  (pull|pull\-requests|pr)[/-]:
    tag: PullRequest
    increment: Inherit
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
